mybatis:  
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.108:3306/springboot?useUnicode=true&characterEncoding=utf-8
    username: kaifa
    password: fuzhaohui
